### ISSUE TITLE
Compatibility with Unity .net 2.0 subset

### ISSUE THREAD

**Issue by Skippeh** [OxideMod/Oxide.CSharp#3]
Is it possible to add support for Unity games that uses the  .net 2.0 subset "optimization"?

This plugin uses RegexOptions.Compiled which does not exist in the subset. I'm not sure if there are more things that are missing.

**Comment by lukespragg** [comment]
You mean the Silverlight edition essentially? That'd probably take a good bit of changes and #if additions to make it work.

**Comment by Skippeh** [comment]
Hmm, maybe? This is the same problem: https://answers.unity.com/questions/223915/regexoptions.html

I don't have unity installed at the moment so i can't easily open and see.

**Comment by lukespragg** [comment]
Yeah, a lot of things won't be under that edition of .NET, and it isn't really something we can add to the game without recreating all of what is missing. It'd probably make more sense to just request that the game developer switches to the full .NET version.

**Comment by Skippeh** [comment]
Alright, i'll try that. Thanks 👍

**Comment by lukespragg** [comment]
Which game is this for?
