### ISSUE TITLE
Oxide throws UnauthorizedAccessException when using lock or ReaderWriterLockSlim 

### ISSUE THREAD

**Issue by steffenWi** [OxideMod/Oxide.CSharp#8]
Hi there,

### Describe your setup

  * Oxide version _("latest" is not a version)_: Oxide.Rust Version: 2.0.3831
  * Game name and version: Rust
  * OS version:Ubuntu Server 16.04 LTS

#### Steps to reproduce:

  1. Create a plugin that uses lock(someObject)
  2. Load the plugin and cause the hook that uses the lock keyword to be triggered

#### Observed results:

Failed to call hook 'OnPlayerSleepEnded' on plugin 'Blamer v0.2.0' (UnauthorizedAccessException: System access is restricted, you are not allowed to use System.Threading.ReaderWriterLockSlim)
  at Oxide.Plugins.Blamer.OnPlayerSleepEnded (.BasePlayer player) [0x00000] in <filename unknown>:0 
  at Oxide.Plugins.Blamer.DirectCallHook (System.String name, System.Object& ret, System.Object[] args) [0x00000] in <filename unknown>:0 
  at Oxide.Plugins.CSharpPlugin.InvokeMethod (Oxide.Core.Plugins.HookMethod method, System.Object[] args) [0x00000] in <filename unknown>:0 
  at Oxide.Core.Plugins.CSPlugin.OnCallHook (System.String name, System.Object[] args) [0x00000] in <filename unknown>:0 
  at Oxide.Core.Plugins.Plugin.CallHook (System.String hook, System.Object[] args) [0x00000] in <filename unknown>:0 

#### Expected results:

No exception should be thrown and the object should be locked.

#### Relevant code _(if applicable)_:
This is an example, the hook doesn't really matter
  ``` csharp
 object someObject = null;
 void OnPlayerSleepEnded(BasePlayer player)
 {
    if (someObject == null)
    {
         lock(someObject) //<--- this is where the exception is thrown
         {
             someObject = new object();
         }
    }
 }
  ```

On the same server I can execute the following program compiled with MonoDevelop as a console project fine:

``` csharp
using System;
using System.Threading;
namespace LockTester
{
    class MainClass
    {
        static ReaderWriterLockSlim testLocker = new ReaderWriterLockSlim();
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            object tester = new object();
            lock(tester)
            {
                Console.WriteLine("lock works!");

            }

            testLocker.EnterReadLock();
            Console.WriteLine("ReadLock works!");
            testLocker.ExitReadLock();
            testLocker.EnterWriteLock();
            Console.WriteLine("WriteLock works!");
            testLocker.ExitWriteLock();
        }
    }
}
```

**Comment by lukespragg** [comment]
It isn't whitelisted so it wouldn't be allowed in plugins.

**Comment by steffenWi** [comment]
Is this 'whitelist' documented somewhere? Because the code compiles just fine. It just fails when the method is called.

**Comment by lukespragg** [comment]
The whitelist is hard-coded in this extension and the game extensions for sandboxing.
